version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - output-volume:/app/Output
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - RUNWAY_API_KEY=${RUNWAY_API_KEY}
      - USE_S3_STORAGE=${USE_S3_STORAGE:-false}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  worker:
    build: .
    command: celery -A chibi_clip.tasks worker --loglevel=info
    volumes:
      - .:/app
      - output-volume:/app/Output
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - RUNWAY_API_KEY=${RUNWAY_API_KEY}
      - USE_S3_STORAGE=${USE_S3_STORAGE:-false}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  output-volume: 